### ISSUE TITLE
Disabling dnsmasq DNS server is unnecessary

### ISSUE THREAD

**Issue by ryao** [cdhowie/netflix-no-ipv6-dns-proxy#17]
I do not like the advice that the README gives to disable dnsmasq's DNS resolver for a few reasons. The first is the dnsmasq is able to enforce dnsmasq and for those using that, disabling it would be a regression in security. The second is that it is unnecessary because dnsmasq is able to forward DNS queries to netflix-no-ipv6-dns-proxy based on domain name. If netflix-no-ipv6-dns-proxy is running on 10.1.1.100, then this would be all that is needed to achieve forwarding for the TLDs and their subdomains:

```
server=/netflix.com/10.1.1.100
server=/nflximg.net/10.1.1.100
server=/nflxext.com/10.1.1.100
server=/nflxvideo.net/10.1.1.100
```

The third reason is that people using dnsmasq and the HE tunnel broker do not need to use netflix-no-ipv6-dns-proxy to unblock netflix. It turns out that a single line in dnsmasq is sufficient to enable netflix to work on my Apple TV and iPhone:

```
host-record=ios.nccp.netflix.com,0100::0
```

I confirmed that not only did things work, but the video traffic was going over IPv4 by observing that the traffic on my HE tunnel was 0 while verifying that netflix would stream.

dnsmasq does not support wildcarding for host-record, so I suspect that other platforms will need additional entries. I assembled a list after reading this article:

http://blog.chrislahaye.com/smart-dns-proxy-to-unblock-netflix-content/

```
host-record=android.nccp.netflix.com,0100::0
host-record=cbp.nccp.netflix.com,0100::0
host-record=ios.nccp.netflix.com,0100::0
host-record=playstation.nccp.netflix.com,0100::0
host-record=nintendo.nccp.netflix.com,0100::0
host-record=nrdp.nccp.netflix.com,0100::0
host-record=xbox.nccp.netflix.com,0100::0
```

It should not be hard to find out what the correct subdomain is for a given device if you use dnsmasq's `log-queries` option, force the device to use the dnsmasq server and grep the dnsmasq.log file for the nccp.netflix.com subdomain.

Anyway, I do not mean to dismiss the excellent work that @cdhowie has done here, but I think that advice for dnsmasq users should be different.

**Comment by cdhowie** [comment]
> The first is the dnsmasq is able to enforce dnsmasq and for those using that, disabling it would be a regression in security.

Can you elaborate on this?  I'm not sure what you mean by "dnsmasq is able to enforce dnsmasq."

> The second is that it is unnecessary because dnsmasq is able to forward DNS queries to netflix-no-ipv6-dns-proxy based on domain name.
>
> ...
>
> dnsmasq does not support wildcarding for host-record, so I suspect that other platforms will need additional entries.

That is precisely the purpose of this proxy: to implement said wildcard.  The alternative is maintaining a list of specific DNS names (which could change without notice), where with a proxy we can just catch them all with a few TLDs.  If dnsmasq could handle wildcards then I would never have written this script.

If you don't want to deploy the proxy for any reason then... just don't?

**Comment by ryao** [comment]
This is a late response, but better late than never. I meant to say dnsmasq is able to enforce dnssec.

As for the proxy, the lack of dnssec support can make things less secure than they are when using dnsmasq. That is why I suggested having instructions for people who already use dnsmasq.

**Comment by unverbraucht** [comment]
I have just tried this and it works like a charm. With my DD-WRT router it was enough to copy the host-record entries to the dnsmasq extra config. Cheers @ryao

**Comment by cdhowie** [comment]
I'm circling back around to this project to clean up a few things and extend support to other services.

After re-reading this issue, I'm going to close it because the issue basically boils down to "don't use this proxy."  While that could be sound advice, it doesn't really describe a specific issue that can be fixed.  If there is a more specific issue or set of issues that can be resolved, feel free to open those as new issues.

**Comment by ryao** [comment]
@cdhowie If I recall correctly, filtering AAAA DNS  query results for just the servers that I listed allows Netflix video traffic to be carried over IPv6, even to blocked address ranges such as the HE tunnel broker. I no longer have Netflix, so I do not know if it changed, but it makes sense that the block list is only enforced on communication with the Netflix authentication servers. Enforcing it elsewhere serves no purpose as far as validating the location of an end user is concerned.

Anyway, this proxy is a great solution for those whose DNS servers do not allow manual blocking, but unless something changed, filtering AAAA records for all Netflix domains is unnecessarily overzealous. It occurred to me that I had neglected to mention that in my initial report, so I am making this addendum.

**Comment by cdhowie** [comment]
@ryao Thanks for the information. My original idea was just to widely block everything over IPv6 because I kept having to add more every few weeks when they changed something.  In my analysis, "overzealous" was another word for "future-proof."
