### ISSUE TITLE
Hi, can your dnsforwarder still work?

### ISSUE THREAD

**Issue by saucebing** [cdhowie/netflix-no-ipv6-dns-proxy#21]
I saw your posts about using HE IPv6 to get access to netflix. I am in the same issue and found your tool seems not working now. Can you still use this?

**Comment by cdhowie** [comment]
I have been using it on my home network and it's been working. What are you having problems with?

**Comment by saucebing** [comment]
I am so happy that you reply so fast! You did a awesome job. Actually my country is China and it is banned by netflix. I have a VPS on Bandwagon.com, when using VPS, I can get access to netflix but will get proxy error when clicking a video. Since my VPS just supports IPv4, so I use HE to create an IPv6 tunnel and I successfully got IPv6 address, and then I use your tool in my VPS. Unfortunately, it still occurs proxy error. I also tried to change dns.AAAA to dns.A to try to use pure IPv6 environment but it failed. Do you have any idea about this situation? I will be very grateful.

By the way, my major is computer science, so I can understand the detail.

**Comment by cdhowie** [comment]
My tool probably can't help you here.

This tool is designed to effectively prohibit Netflix from using IPv6 and force it to use IPv4. This only works if your IPv4 connection is not blocked by Netflix as a proxy.

From your description, it looks like both your IPv4 and IPv6 networks are flagged as a proxy by Netflix.  In this situation, there's nothing my tool can do for you.

**Comment by saucebing** [comment]
Thank you anyway.

**Comment by cdhowie** [comment]
No problem, sorry I couldn't be of more help.
