### ISSUE TITLE
Error while enable systemctl

### ISSUE THREAD

**Issue by mnathani** [cdhowie/netflix-no-ipv6-dns-proxy#4]
root@esx2:/opt# ln -s /opt/netflix-no-ipv6-dns-proxy/netflix-no-ipv6-dns-proxy.service /etc/systemd/system/
root@esx2:/opt# systemctl enable netflix-no-ipv6-dns-proxy.service
Failed to execute operation: Too many levels of symbolic links

**Comment by jamesmacwhite** [comment]
Is `/etc/systemd/system` itself a symlink?

**Comment by mnathani** [comment]
It is not.

I copied netflix-no-ipv6-dns-proxy.service into the /etc/systemd/system
folder directly and it seems to work now

**Comment by cdhowie** [comment]
I think there are versions of systemd that don't like symlinked unit files.  You can omit the `-s` option to create a hardlink instead, or just copy it (as you have done).  I will update the documentation to account for this.
